#include <cassert>
#include <cstdio>
#include <iostream>
#include <fstream>
#include "../app/simpleCompressor/count_char.hpp"

using namespace std;

int main(int argc, char const *argv[])
{
    cout << "start testing count_char" << endl;

    string testFilePath("test.txt");

    // generate the file for testing
    ofstream fileStream(testFilePath);
    string testString("iunfh ao475v20893475y27\n\nhiasuhh41965   uadf");
    int trueCharCount[256] = {0};
    /* the code bellow is generated by a simple python script: 
    for i in range(256):
        if chr(i) in string:
            print(f"trueCharCount['{chr(i)}'] = {string.count(chr(i))};")
    */
    trueCharCount['\n'] = 2;
    trueCharCount[' '] = 4;
    trueCharCount['0'] = 1;
    trueCharCount['1'] = 1;
    trueCharCount['2'] = 2;
    trueCharCount['3'] = 1;
    trueCharCount['4'] = 3;
    trueCharCount['5'] = 3;
    trueCharCount['6'] = 1;
    trueCharCount['7'] = 3;
    trueCharCount['8'] = 1;
    trueCharCount['9'] = 2;
    trueCharCount['a'] = 3;
    trueCharCount['d'] = 1;
    trueCharCount['f'] = 2;
    trueCharCount['h'] = 4;
    trueCharCount['i'] = 2;
    trueCharCount['n'] = 1;
    trueCharCount['o'] = 1;
    trueCharCount['s'] = 1;
    trueCharCount['u'] = 3;
    trueCharCount['v'] = 1;
    trueCharCount['y'] = 1;
    if (fileStream.is_open())
    {
        fileStream << testString;
    }
    else
        assert(false);
    fileStream.close();

    ifstream testFileStream(testFilePath);
    int charCount[256] = {0};
    if (testFileStream.is_open())
    {
        // the test itself (finally)
        countChar(testFileStream, charCount);
    }
    else
        assert(false);
    
    for (size_t i = 0; i < 256; i++)
    {
        assert(charCount[i] == trueCharCount[i]);
    }

    testFileStream.close();
    remove(testFilePath.c_str());
    cout << "test passed." << endl;
    return 0;
}
